import React, { Component } from 'react';

class About extends Component {
  render () {
    return (
      <div>
        <p>Hi! My name is Nick. I serve as a Technical Instructor at the Thayer School of Engineering at Dartmouth College. I teach problem-solving, machine shop safety, and a broad range of technical skills ranging from introductory manual machining to CAD / CAM Programming / CNC machining. I also support student teams with guidance on diverse issues including fabrication, design for manufacturability, and project management. I am honored to be part of a small instructional team that includes full-time professionals as well as student Teaching Assistants who work together to provide the best education possible for engineers at Thayer.</p>
        <p>I graduated from Thayer with a B.E. in Mechanical Engineering in 2011 and a Master of Engineering Management in 2012. My main non-academic focus during that time involved serving extensively as a volunteer in a student-led non-profit organization called Dartmouth Humanitarian Engineering. Some of that experience involved working on the ground in Kenya on a clean water project, leading an assessment for a possible sanitation project in the Dominican Republic, optimizing the power output of a hydropower turbine design, and leading the organization as President for a year. I enjoyed working with people on impactful technical projects and maximizing the impact of my colleagues' efforts through effective communication and leadership.</p>
        <p>I also did two internships (one as an Accounting Intern at a software company called BitTorrent, and one as an Analyst Intern at a small investment bank). My first job after Dartmouth was as an Analyst at an investment bank, but I quickly realized that the lifestyle of the finance industry did not suit me. I transitioned into a career as a precision machinist where I could leverage my technical education and develop my hands-on manufacturing skills.</p>
        <p>I worked as a CNC Mill Machinist in the automotive industry for half a year, and then worked as a Senior CNC Lathe Machinist and Programmer at a helicoptor gear shop for almost 3 years. This experience significantly developed my machine shop skills, led me to deeper understanding of many challenges faced in precision manufacturing, and provided me with a chance to train junior machinists.</p>
        <p>In early 2017, I left my position in the aerospace industry and spent the year focusing on software engineering through independent study as well as completion of the Back-End Software Engineering program at an excellent private school in Denver called Turing. My motivation for this is the increasing relevance of software in all engineering disciplines, as well as a desire to participate in the diverse, inclusive, supportive community at Turing. I have gained knowledge of modern software engineering practices like Object-Oriented Programming, Test-Driven Development, Version Control, and Database Design. I have also learned specific programming technologies like machine-to-machine communication with HTTP and WebSockets, database interaction with SQL, web server implementation with both Ruby on Rails and Node.js/Express.js, and front-end display with JavaScript/HTML/CSS. This was all in a highly collaborative setting, providing deep experience in developing software in teams.</p>
        <p>This professional experience has enabled me to be a highly valuable mentor and technical resource for budding engineers. I look forward to continuing my own journey while supporting the growth of others. The choice to be of service to others strikes me as the highest calling, and so I approach my career as a teacher with a sense of utmost respect for all of the individuals and institutions I work with. In service, onward we go.</p>
      </div>
    );
  }
}

export default About;
